[package]
name = "ComposableToken"
version = "0.2.0"
authors = ["lay (Aladeen)"]

[addresses]
composable_token = "_"
# TODO: remove before deploying
contract_obj = "0x1337"

[dev-addresses]

[dependencies.TokenMinter]
local = "./TokenMinter"

[dev-dependencies]

