[package]
name = "ComposableToken"
version = "0.2.0"
authors = ["lay (Aladeen)"]

[addresses]
composable_token = "0x9de4ffd4d4e5d8463d0a8f7aea8d6f7a936006face568763cac335fe553fc8bb"

[dev-addresses]

[dependencies.TokenMinter]
local = "./TokenMinter"

[dev-dependencies]

