[package]
name = "Composables"
version = "0.2.0"
authors = ["lay (Aladeen)"]

[addresses]
composable_token = "0xacf659101f2f39123e5c9ff5486100c78a84d2ab8319c52e3795aeb29ea8db3a"
minter = '_'

[dev-addresses]
minter = "0x123"

[dependencies.TokenMinter]
git = 'https://github.com/aptos-labs/token-minter.git'
rev = 'main'
subdir = 'token-minter/'

[dev-dependencies]

