[package]
name = "ComposableToken"
version = "0.2.0"
authors = ["lay (Aladeen)"]

[addresses]
composable_token = "0x2211f3ce180f03d754a8be1ad7f91f976aedd67b7f59c4a450a12e05cb468ab6"


[dev-addresses]

[dependencies.TokenMinter]
local = "./TokenMinter"

[dev-dependencies]

