[package]
name = "Examples"
version = "1.0.0"
authors = ["lay (Aladeen)"]

[addresses]
composable_token = "0x8593ad8f01f11dece1099b71187922e6350d4da6c28726078d65a02523dbe190"
examples = "0xeffb9356ede780467b845c6ae6ec90592b5293f44392ddb39b1776ba72f64a83"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

# to be updated
[dependencies.Composables]
git = "https://github.com/TowneSquare/TowneSpace-contract"
rev = "devnet"
subdir = "composables"

# to be updated
[dependencies.Studio-alpha]
git = "https://github.com/TowneSquare/TowneSpace-contract"
rev = "devnet"
subdir = "studio"

[dev-dependencies]
